dependencies:
  flutter:
    sdk: flutter

  # Firebase Core Services
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  firebase_storage: ^12.0.0

  # QR Code Scanner
  mobile_scanner: ^4.0.0

  # State Management
  flutter_riverpod: ^3.0.0 # or provider if you prefer

  # Routing
  go_router: ^13.0.0

  # UI / Utility
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^3.0.0
  intl: ^0.19.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
